# Generated by Django 3.2.6 on 2024-04-25 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OTP', '0002_otp_is_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='is_used',
        ),
    ]
