version: '3'

services:
  web:
    build: .
    volumes:
      - ./:/usr/src/app/
    image: work_log.cms:latest
    container_name: work_log
    ports:
      - 8000:8000
      - 6969:6969
    env_file:
      - ./.env.dev
  # nginx:
  #   build: ./nginx
  #   volumes:
  #     - ./:/usr/src/app/
  #   image: services.nginx:latest
  #   container_name: nginx_vape
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - web