version: '3'

services:

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'TimekeepingExnodes'
      MYSQL_USER: 'gkayz'
      MYSQL_PASSWORD: '123456789'
      MYSQL_ROOT_PASSWORD: '123456789'
    ports:
      - '3307:3306'
    networks:
      - my_network
    command: --bind-address=0.0.0.0


  web:
    build: .
    volumes:
      - ./:/usr/src/app/
    image: work_log.cms:latest
    container_name: work_log
    ports:
      - 8000:8000
      - 6969:6969
    env_file:
      - ./.env.dev
    networks:
      - my_network
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    
networks:
  my_network:
    driver: bridge
    
    

  # nginx:
  #   build: ./nginx
  #   volumes:
  #     - ./:/usr/src/app/
  #   image: services.nginx:latest
  #   container_name: nginx_vape
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - web
