# Generated by Django 3.2.6 on 2024-04-22 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JWTToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500)),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=30)),
                ('roles', models.CharField(max_length=50)),
                ('issued_at', models.DateTimeField()),
                ('expiration_time', models.DateTimeField()),
                ('issuer', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('audience', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=100)),
                ('user_agent', models.CharField(max_length=100)),
                ('device_id', models.CharField(max_length=100)),
            ],
        ),
    ]
