# Generated by Django 3.2.6 on 2024-04-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JWTToken', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jwttoken',
            name='is_expired',
            field=models.BooleanField(default=True),
        ),
    ]
