# Generated by Django 3.2.6 on 2024-05-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveRequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
