# Generated by Django 3.2.6 on 2024-05-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaveRequest', '0003_alter_leaverequest_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='created_at',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
