# Generated by Django 3.2.6 on 2024-05-07 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=256)),
                ('status', models.BooleanField(default=True)),
                ('platform', models.CharField(choices=[('WEB', 'Web'), ('ANDROID', 'Android'), ('IOS', 'Ios')], default='WEB', max_length=10)),
                ('language', models.CharField(default='en', max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviceTokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.JSONField(default=None, null=True)),
                ('message', models.JSONField(default=None, null=True)),
                ('payloadData', models.JSONField(default=None, null=True)),
                ('isRead', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('deviceToken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviceTopics', to='Notification.devicetoken')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviceTopics', to='Notification.topic')),
            ],
        ),
    ]
