# Generated by Django 3.2.6 on 2024-05-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0005_alter_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='imageURL',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
