# Generated by Django 3.2.6 on 2024-05-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0006_employee_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='imageURL',
        ),
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='employee_images/'),
        ),
    ]
