# Generated by Django 5.0.4 on 2024-04-23 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timekeeping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('CHECKIN', 'Checkin'), ('CHECKOUT', 'Checkout')], default='CHECKIN', max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('check_time', models.TimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_keeping', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
