# Generated by Django 3.2.6 on 2024-04-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timekeeping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timekeeping',
            name='check_type',
            field=models.CharField(choices=[('CHECKIN', 'Checkin'), ('CHECKOUT', 'Checkout'), ('RAVAO', 'Ra vào')], default='CHECKIN', max_length=10),
        ),
    ]
