# Generated by Django 3.2.6 on 2024-05-02 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='month',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='salary',
            name='year',
            field=models.IntegerField(default=1),
        ),
    ]
