# Generated by Django 3.2.6 on 2024-05-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salary', '0002_auto_20240502_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
