# Generated by Django 3.2.6 on 2024-05-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salary', '0003_alter_salary_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
